import type { PlansType } from "@aperturs/validators/subscription";

export const Plans = [
  {
    variantName: "montly",
    description: null,
    price: "6000.000000000000",
    interval: "month",
    intervalCount: 1,
    isUsageBased: false,
    productId: 174109,
    productName: "business",
    variantId: 224378,
    trialIntervalCount: 0,
    sort: 3,
    power: 3,
  },
  {
    variantName: "Yearly",
    description: null,
    price: "60000.000000000000",
    interval: "year",
    intervalCount: 1,
    isUsageBased: false,
    productId: 174109,
    productName: "business",
    variantId: 224379,
    trialInterval: "day",
    trialIntervalCount: 14,
    sort: 3,
    power: 6,
  },
  {
    variantName: "Monthly",
    description: null,
    price: "2500.000000000000",
    interval: "month",
    intervalCount: 1,
    isUsageBased: false,
    productId: 174106,
    productName: "small business",
    important: true,
    variantId: 224369,
    trialIntervalCount: 0,
    sort: 2,
    power: 2,
  },
  {
    variantName: "Yearly",
    description: null,
    price: "25000.000000000000",
    interval: "year",
    intervalCount: 1,
    isUsageBased: false,
    productId: 174106,
    important: true,
    productName: "small business",
    variantId: 224373,
    trialInterval: "day",
    trialIntervalCount: 14,
    sort: 2,
    power: 5,
  },
  {
    variantName: "Yearly pricing",
    description: "<p>yearly pricing</p>",
    price: "14000",
    interval: "year",
    intervalCount: 1,
    isUsageBased: false,
    productId: 113580,
    productName: "Solo Creator",
    variantId: 129346,
    trialInterval: "day",
    trialIntervalCount: 14,
    sort: 1,
    power: 4,
  },
  {
    variantName: "monthly",
    description: null,
    price: "1400",
    interval: "month",
    intervalCount: 1,
    isUsageBased: false,
    productId: 113580,
    productName: "Solo Creator",
    variantId: 129349,
    trialInterval: "day",
    trialIntervalCount: 14,
    sort: 1,
    power: 1,
  },
] as PlansType[];
