import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@aperturs/ui/globals.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// const mona = localFont({
//   src: 'mona-sans.woff2',
//   display: 'swap',
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="preload" href="Mona-Sans.woff2" as="font" type="font/woff2" crossOrigin="anonymous"></link>
      <body>{children}</body>
    </html>
  );
}
